#!/usr/bin/env bash
# Regenerates every fixture under this directory from its sources. The
# `fixtures` menu command runs this script with the flake's `wasm-tools`
# and `wac` on the PATH, so the outputs are reproducible byte for byte.
#
# Each fixture directory holds a WIT package, one core module in WAT per
# world, and `assertions.wast`. This script builds each core module into
# a component with `wasm-tools component embed` + `wasm-tools component
# new`, composes with `wac plug` where a fixture has a socket, and writes
# `<fixture>.wast` next to the directory: the final component as a
# `(component binary ...)` directive followed by the assertions. The
# conformance harness runs those `.wast` files like the vendored corpora.
set -euo pipefail
cd "$(dirname "$0")"

# Write a component binary as a `(component $name binary "...")`
# directive, 32 bytes per line so the file diffs line by line.
binary_directive() { # name, path
  echo "(component \$$1 binary"
  od -An -v -tx1 -w32 "$2" | sed -e 's/ /\\/g' -e 's/^/    "/' -e 's/$/"/'
  echo ")"
}

# Emit the `.wast` for one fixture: a header, the binary directive, and
# the hand-written assertions.
emit_wast() { # fixture, name, binary
  {
    echo ";; Generated by \`fixtures\` from $1/. Do not edit by hand: the"
    echo ";; sources are the WIT, the WAT, and assertions.wast in that directory."
    echo
    binary_directive "$2" "$3"
    echo
    cat "$1/assertions.wast"
  } > "$1.wast"
}

# guest: one core module, one world, one component.
wasm-tools component embed --world guest guest/guest.wit guest/guest.wat -o guest/guest.core.wasm
wasm-tools component new guest/guest.core.wasm -o guest/guest.wasm
rm guest/guest.core.wasm
emit_wast guest guest guest/guest.wasm

# composition: a plug that exports `math` and a socket that imports it,
# each a component of its own, then composed with `wac plug`.
wasm-tools component embed --world plug composition/math.wit composition/plug.wat -o composition/plug.core.wasm
wasm-tools component new composition/plug.core.wasm -o composition/plug.wasm
wasm-tools component embed --world socket composition/math.wit composition/socket.wat -o composition/socket.core.wasm
wasm-tools component new composition/socket.core.wasm -o composition/socket.wasm
rm composition/plug.core.wasm composition/socket.core.wasm
wac plug --plug composition/plug.wasm composition/socket.wasm -o composition/composed.wasm
emit_wast composition composed composition/composed.wasm

# The harness manifest: one `corpus_test!` per `.wast` under the corpus
# and the table the progress summary reads. A fixture's own directory
# holds only sources (its `assertions.wast` is not a runnable script), so
# those are skipped.
manifest=../../conformance/manifest.rs
files=$(cd .. && LC_ALL=C find . -name '*.wast' -not -path './fixtures/*/*' | sed 's|^\./||' | LC_ALL=C sort)
{
  echo "// Generated by \`fixtures\` from the files under \`tests/corpus/\`. Rerun"
  echo "// that command when a file is added or removed."
  echo
  for path in $files; do
    name=$(printf '%s' "${path%.wast}" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]\+/_/g' -e 's/^_//' -e 's/_$//')
    echo "corpus_test!(it_passes_$name, \"$path\");"
  done
  echo
  echo "/// Every corpus file with its text, for the progress summary."
  echo "const CORPUS_FILES: &[(&str, &str)] = &["
  for path in $files; do
    echo "    (\"$path\", include_str!(\"../corpus/$path\")),"
  done
  echo "];"
} > "$manifest"

echo "fixtures regenerated"
