// Copyright 2026 The Dialog DB Project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// The contract between the two programs. Each program compiles against
// the world named after it.
package wcmp:check-link;

interface greeter {
  greet: async func(name: string) -> string;
}

world exporter {
  export greeter;
}

world importer {
  import greeter;
  export welcome: async func(name: string) -> string;
}
