// Copyright 2026 The Dialog DB Project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Two worlds that do not compose: the exporter exports `farewell`, and
// the importer imports `greeter`.
package wcmp:unplugged;

interface greeter {
  greet: func(name: string) -> string;
}

interface farewell {
  part: func(name: string) -> string;
}

// The world of `exporter.zena`.
world exporter {
  export farewell;
}

// The world of `importer.zena`.
world importer {
  import greeter;
  export welcome: func(name: string) -> string;
}
