[package]
name = "wasm-component-model-polyfill"
description = "A polyfill bringing the WebAssembly Component Model (wasip3) to web browsers"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
# Integration tests that drive a real browser via WebDriver.
web-integration-tests = []

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wasm_runtime_layer = { workspace = true }
wasmparser = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "sync"] }
wasmtime_runtime_layer = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
js-sys = { workspace = true }
js_wasm_runtime_layer = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
wasm-bindgen-test = { workspace = true }
wcmp-macros = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
wasmtime = { workspace = true, features = ["gc-drc"] }
